//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.ContaCorrente.Domain.Mensagem {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagens {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagens() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.ContaCorrente.Domain.Mensagem.Mensagens", typeof(Mensagens).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0011| Banco informado não existe..
        /// </summary>
        public static string BancoInvalido {
            get {
                return ResourceManager.GetString("BancoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0007| Banco {0} já existe na base..
        /// </summary>
        public static string BancoJaExistente {
            get {
                return ResourceManager.GetString("BancoJaExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0017| Correntista informado não existe..
        /// </summary>
        public static string CorrentistaInvalido {
            get {
                return ResourceManager.GetString("CorrentistaInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0006| Data invalida..
        /// </summary>
        public static string DataInvalida {
            get {
                return ResourceManager.GetString("DataInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0010| Endereço informado não existe..
        /// </summary>
        public static string EnderecoInvalido {
            get {
                return ResourceManager.GetString("EnderecoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0005| Entidade {0} não pode ser carregada..
        /// </summary>
        public static string EntidadeNaoCarregada {
            get {
                return ResourceManager.GetString("EntidadeNaoCarregada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0008| Entidade não encontrada..
        /// </summary>
        public static string EntidadeNaoEncontrada {
            get {
                return ResourceManager.GetString("EntidadeNaoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0002| Erro ao alterar entidade..
        /// </summary>
        public static string ErroAoAlterarEntidade {
            get {
                return ResourceManager.GetString("ErroAoAlterarEntidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0003| Erro ao atualizar entidade..
        /// </summary>
        public static string ErroAoAtualizarEntidade {
            get {
                return ResourceManager.GetString("ErroAoAtualizarEntidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0016| Não foi possível atualizar o saldo..
        /// </summary>
        public static string ErroAoAtualizarSaldo {
            get {
                return ResourceManager.GetString("ErroAoAtualizarSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0001| Erro ao criar entidade..
        /// </summary>
        public static string ErroAoCriarEntidade {
            get {
                return ResourceManager.GetString("ErroAoCriarEntidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0020| Não foi possível gerar as parcelas do emprestimo..
        /// </summary>
        public static string ErroAoCriarParcelasEmprestimo {
            get {
                return ResourceManager.GetString("ErroAoCriarParcelasEmprestimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0014| Não foi possível criar saldo da conta corrente..
        /// </summary>
        public static string ErroAoCriarSaldoContaCorrente {
            get {
                return ResourceManager.GetString("ErroAoCriarSaldoContaCorrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0009| Erro ao deletar entidade..
        /// </summary>
        public static string ErroAoDeletarEntidade {
            get {
                return ResourceManager.GetString("ErroAoDeletarEntidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0019| Erro ao efetivar emprestimo..
        /// </summary>
        public static string ErroAoEfetivarEmprestimo {
            get {
                return ResourceManager.GetString("ErroAoEfetivarEmprestimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0004| Erro ao efetuar consulta dos dados..
        /// </summary>
        public static string ErroAoEfetuarConsulta {
            get {
                return ResourceManager.GetString("ErroAoEfetuarConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0018| Historico informado não existe..
        /// </summary>
        public static string HistoricoInvalido {
            get {
                return ResourceManager.GetString("HistoricoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0013| Local de trabalho não existe, deve ser informado para pessoa física..
        /// </summary>
        public static string LocalTrabalhoInvalido {
            get {
                return ResourceManager.GetString("LocalTrabalhoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Não foi possível completar a operação..
        /// </summary>
        public static string NaoFoiPossivelCompletarOperacao {
            get {
                return ResourceManager.GetString("NaoFoiPossivelCompletarOperacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0012| Pessoa informada não existe..
        /// </summary>
        public static string PessoaInvalida {
            get {
                return ResourceManager.GetString("PessoaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 0015| Saldo insuficiente para fazer a operação..
        /// </summary>
        public static string SaldoInsuficiente {
            get {
                return ResourceManager.GetString("SaldoInsuficiente", resourceCulture);
            }
        }
    }
}
